### ISSUE TITLE
GitOps Principles Sync Mar 29, 2021

### ISSUE THREAD

**Issue by scottrigby** [open-gitops/principles#1]
### Update

Meeting notes have been transferred to the main GWG meeting notes doc, so everyone can contribute to notes.

Link for this week's notes: https://docs.google.com/document/d/1hxifmCdOV5_FbKloDJRWZQHq0ge-trXJKF-BgV4wHVk/edit#heading=h.lfuaf62iclbk

**Comment by tonit** [comment]
Can't edit, so:
Brice Fernandes
Christian Hernandez
Leonardo Murillo
Lothar Schulz
Moshe Immerman
Roberth Strand
Scott Rigby 
Toni Menzel

**Comment by scottrigby** [comment]
Updated description above. Meeting notes transferred to Google doc
